In [17]:
import pandas as pd

data_01 = pd.read_csv('../data/0.1_results_fix_interval.csv')
data_02 = pd.read_csv('../data/0.2_results_fix_interval.csv')
data_03 = pd.read_csv('../data/0.3_results_fix_interval.csv')
data_04 = pd.read_csv('../data/0.4_results_fix_interval.csv')
data_05 = pd.read_csv('../data/0.5_results_fix_interval.csv')
data_06 = pd.read_csv('../data/0.6_results_fix_interval.csv')
data_07 = pd.read_csv('../data/0.7_results_fix_interval.csv')
data_08 = pd.read_csv('../data/0.8_results_fix_interval.csv')
data_09 = pd.read_csv('../data/0.9_results_fix_interval.csv')

In [18]:
frames = [data_02, data_03, data_04, data_05, data_06, data_07, data_08, data_09]
data = pd.concat(frames)

In [32]:
subdata = data[(data['nr'] == 1) & (data['nazwa'] == 2) & (data['pp'] == 0.3) & (data['numberOfSeeds'] == 8) & (data['interval'] == 2)]

In [33]:
# subdata.apply(lambda x: print(x), axis=1)
subdata

,nr,nazwa,pp,numberOfSeeds,seeds,totalNumberOfSeeds,numberOfNodes,step,infectedPerStep,infectedTotal,infectedTotalPercentage,computionalTime,interval
742,1,2,0.3,8,"[103, 9, 105, 400, 32, 3, 41, 42]",8,1899,1,398,406,21.379674,0:00:00.962037,2
743,1,2,0.3,8,"[249, 1283, 357, 840, 19, 704, 204, 176]",16,1899,2,688,1102,58.030542,0:00:00.300063,2
744,1,2,0.3,8,"[249, 1283, 357, 840, 19, 704, 204, 176]",16,1899,3,282,1384,72.880463,0:00:00.300063,2
745,1,2,0.3,8,"[1712, 1862, 1801, 1876, 10, 22, 137, 160]",24,1899,4,23,1415,74.512902,0:00:00.002433,2
746,1,2,0.3,8,"[1712, 1862, 1801, 1876, 10, 22, 137, 160]",24,1899,5,3,1418,74.670879,0:00:00.002433,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
130228,1,2,0.3,8,"[870, 1010, 1245, 24, 395, 130, 1694, 130]",486,1899,123,0,1886,99.315429,0:00:00.000070,2
130229,1,2,0.3,8,"[628, 628, 601, 685, 956, 1607, 956, 1884]",492,1899,124,0,1892,99.631385,0:00:00.000070,2
130230,1,2,0.3,8,"[628, 628, 601, 685, 956, 1607, 956, 1884]",492,1899,125,0,1892,99.631385,0:00:00.000070,2
130299,1,2,0.3,8,"[433, 902, 1720, 1825, 906, 1422, 1254, 1614]",511,1899,66,0,1899,100.000000,0:00:00.000087,2
130300,1,2,0.3,8,"[433, 902, 1720, 1825, 906, 1422, 1254, 1614]",511,1899,67,0,1899,100.000000,0:00:00.000087,2